# Generated by Django 5.1.4 on 2024-12-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_alter_student_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='recepie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='recepie')),
            ],
        ),
        migrations.DeleteModel(
            name='car',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
